name: Generate Offline Documentation

on:
  workflow_run:
    workflows: ["Deploy static content to Pages"]
    types:
      - completed

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: jekyll-gh-pages.yml
          workflow_conclusion: success
          name: docusaurus-build
          path: build/

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Convert HTML to Markdown
        run: |
          mkdir -p build/markdown
          for file in build/**/*.html; do
              pandoc "$file" -f html -t markdown -o "build/markdown/$(basename "$file" .html).md"
          done

      - name: Upload markdown artifact
        uses: actions/upload-artifact@v2
        with:
          name: offline-docs
          path: build/markdown/

      - name: Generate PDF from markdown (optional)
        run: |
          npx markdown-pdf build/markdown/**/*.md

      - name: Upload PDF artifact (optional)
        uses: actions/upload-artifact@v2
        with:
          name: offline-docs-pdf
          path: build/markdown/**/*.pdf