name: Generate Offline Documentation

on:
  workflow_run:
    workflows: ["Deploy static content to Pages"]
    types:
      - completed

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Install Prince
          run: |
            curl https://www.princexml.com/download/prince-14.2-linux-generic-x86_64.tar.gz -O
            tar zxf prince-14.2-linux-generic-x86_64.tar.gz
            cd prince-14.2-linux-generic-x86_64
            yes "" | sudo ./install.sh

        - name: Clone forked Custom-docusaurus-prince-pdf
          run: |
            git clone https://github.com/FinalFactory/Custom-docusaurus-prince-pdf.git
            cd Custom-docusaurus-prince-pdf
            npm install -g

        - name: Build PDF Offline Docu Tagger
          run: |
            cd Custom-docusaurus-prince-pdf
            npx custom-docusaurus-prince-pdf -u https://docs.finalfactory.de/docs/category/final-tagger --output FinalTagger-Offline-Documentation.pdf --category-stop
        - name: Build PDF Offline Docu Preferences
          run:  |
            cd Custom-docusaurus-prince-pdf
            npx custom-docusaurus-prince-pdf -u https://docs.finalfactory.de/docs/category/final-preferences --output FinalPreferences-Offline-Documentation.pdf --category-stop
  
        - name: Upload results Tagger
          uses: actions/upload-artifact@v3
          with:
            name: result
            # The output filename can be specified with --output option
            path: FinalTagger-Offline-Documentation.pdf
            if-no-files-found: error
        - name: Upload results Preferences
          uses: actions/upload-artifact@v3
          with:
            name: result
            # The output filename can be specified with --output option
            path: FinalPreferences-Offline-Documentation.pdf
            if-no-files-found: error