name: Generate Offline Documentation

on:
  workflow_run:
    workflows: ["Deploy static content to Pages"]
    types:
      - completed

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Install Prince
          run: |
            curl https://www.princexml.com/download/prince-14.2-linux-generic-x86_64.tar.gz -O
            tar zxf prince-14.2-linux-generic-x86_64.tar.gz
            cd prince-14.2-linux-generic-x86_64
            yes "" | sudo ./install.sh
  
        - name: Build PDF
          run: npx docusaurus-prince-pdf -u https://docs.finalfactory.de/docs/preferences/intro
  
        - name: Upload results
          uses: actions/upload-artifact@v3
          with:
            name: result
            # The output filename can be specified with --output option
            path: pdf/FinalPreferences.pdf
            if-no-files-found: error